routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PostController@index')->name('home');

Auth::routes();

Route::get('comments/create/{post_id}', 'CommentController@create');
Route::get('comments/create', 'PostController@index');

Route::resource('authors', 'AuthorController');
Route::resource('posts', 'PostController');
Route::resource('comments', 'CommentController');

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'title', 'content', 'author_id',
    ];

    public function author()
    {
        return $this->belongsTo('App\Author');
    }

    public function comments()
    {
        return $this->hasMany('App\Comment');
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Post;
use App\Http\Requests\StorePost;
use Illuminate\Http\Request;

class PostController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth', ['except' => ['index', 'show']]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts = Post::all();

        return view('posts.index', compact('posts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $author = auth()->user()->author;

        return view('posts.create', compact('author'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StorePost $request)
    {
        $post = Post::create($request->validated());

        // TODO: fire an event, like https://laravel.com/docs/5.8/events#dispatching-events
        // event(new PostStored($post));
        return redirect()->route('posts.show', ['id' => $post->id]);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post)
    {
        return view('posts.show', compact('post'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {
        return view('posts.edit', compact('post'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function update(StorePost $request, Post $post)
    {
        $validated = $request->validated();

        $post->title = $validated['title'];
        $post->content = $validated['content'];
        $post->save();

        // TODO: fire an event, like https://laravel.com/docs/5.8/events#dispatching-events
        // event(new PostUpdated($post));
        return redirect()->route('posts.show', ['id' => $post->id]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function destroy(Post $post)
    {
        $return_id = $post->id;
        $succeeded = $post->delete();

        if ($succeeded) {
            $message = 'Post is successfully deleted';
        } else {
            $message = 'Post failed to be deleted';
        }

        // TODO: fire an event, like https://laravel.com/docs/5.8/events#dispatching-events
        // event(new PostDestroyed($post));
        return redirect()->route('posts.show', ['id' => $return_id])->with('status', $message);
    }
}

resources/views/posts/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card-body">
                @if (session('status'))
                    <div class="alert alert-success" role="alert">
                        {{  session('status') }}
                    </div>
                @endif

                <div class="card uper">
                    <div class="card-header">
                        Add Post
                    </div>
                    <div class="card-body">
                        @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                <li>{{  $error }}</li>
                                @endforeach
                            </ul>
                        </div><br />
                        @endif
                        <form method="post" action="{{ route('posts.store') }}">

                            @csrf
                            <input type='hidden' name='author_id' value='{{ $author->id }}'>

                            <div class="form-group">
                                <label for="name">Post Title:</label>
                                <input type="text" class="form-control" name="title"/>
                            </div>
                            <div class="form-group">
                                <label for="content">Post Content :</label>
                                <textarea class="form-control" name="content"></textarea>
                            </div>

                            <p class='small'>
                                author id:{{ $author->id }}
                                author name:{{ $author->name }}
                                author ip:{{ $author->ip }}
                            </p>

                            <button type="submit" class="btn btn-primary">Create Post</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/posts/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card-body">
                @if (session('status'))
                    <div class="alert alert-success" role="alert">
                        {{ session('status') }}
                    </div>
                @endif

                <div class="card uper">
                    <div class="card-header">
                        Edit Post
                    </div>
                    <div class="card-body">
                        @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div><br />
                        @endif
                        <form method="post" action="{{ route('posts.update', $post->id) }}">

                            @csrf
                            @method('PATCH')
                            <input type='hidden' name='author_id' value='{{ $post->author->id }}'>

                            <div class="form-group">
                                <label for="name">Post Title:</label>
                                <input type="text" class="form-control" name="title" value="{{ $post->title }}"/>
                            </div>
                            <div class="form-group">
                                <label for="content">Post Content :</label>
                                <textarea class="form-control" name="content">{{ $post->content }}</textarea>
                            </div>

                            <p class='small'>
                                author id:{{ $post->author->id }}
                                author name:{{ $post->author->name }}
                                author ip:{{ $post->author->ip }}

                            <button type="submit" class="btn btn-primary">Update Post</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/posts/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card-body">
                @if (session('status'))
                    <div class="alert alert-success" role="alert">
                        {{ session('status') }}
                    </div>
                @endif

                <div class="card uper">
                    <div class="card-header">
                        <h1>Posts</h1>
                        <form action="{{ route('posts.create' ) }}" method="get">
                            @csrf
                            <button class="btn btn-primary" type="submit">add post</button>
                        </form>
                    </div>
                    <div class="card-body">
                        @foreach($posts->sortBy('updated_at')->reverse() as $post)
                            <p>
                                <a href="{{ route('posts.show', $post->id) }}">{{ $post->title }}</a> ({{ $post->id }})<br/>
                                <span class='small'>{{ $post->updated_at }}</span>
                            </p>
                        @endforeach
                    </div>

                    <form action="{{ route('posts.create' ) }}" method="get">
                        @csrf
                        <button class="btn btn-primary" type="submit">add post</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/posts/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card-body">
                @if (session('status'))
                    <div class="alert alert-success" role="alert">
                        {{ session('status') }}
                    </div>
                @endif

                <form action="{{ route('posts.index' ) }}" method="get">
                    @csrf
                    <button class="btn btn-primary" type="submit">all posts</button>
                </form>&nbsp;

                <div class="card uper">
                    <div class="card-header">
                        <h1>{{ $post->title }}</h1>
                        <p class='small'>
                        id::{{ $post->id}}
                        created_at::{{ $post->created_at   }}
                        updated_at::{{ $post->updated_at   }}
                        author->id::{{ $post->author->id   }}
                        author->name::{{ $post->author->name }}
                        author->ip::{{ $post->author->ip   }}
                        </p>
                    </div>
                    <div class="card-body">
                        {{ $post->content}}<br/><br/>
                    </div>
                </div>
                <div class="card uper">
                    <div class="card-header">
                        <h3>Comments</h3>

                        <form action="{{ route('comments.create' ) }}/{{ $post->id }}" method="get">
                            @csrf
                            <button class="btn btn-primary" type="submit">add comment</button>
                        </form>
                    </div>
                    <div class="card-body">

                        @foreach($post->comments->sortBy('updated_at')->reverse() as $comment)
                        <div class="card uper">
                            <div class="card-header">
                                <a href="{{ route('comments.show', $comment->id)}}">{{ $comment->title}}</a> ::id::{{ $comment->id}}
                                <p class='small'>
                                    {{ $comment->created_at   }}
                                    {{ $comment->updated_at   }}
                                    {{ $comment->author->id   }}
                                    {{ $comment->author->name }}
                                    {{ $comment->author->ip   }}
                                </p>
                            </div>
                            <div class="card-body">
                                {{ $comment->content }}
                            </div>
                        </div>
                        @endforeach

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection