routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PostController@index')->name('home');

Auth::routes();

Route::get('comments/create/{post_id}', 'CommentController@create');
Route::get('comments/create', 'PostController@index');

Route::resource('authors', 'AuthorController');
Route::resource('posts', 'PostController');
Route::resource('comments', 'CommentController');

app/Comment.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Comment extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'title', 'content', 'author_id', 'post_id',
    ];
    public   $rules = [
        'title' => 'required',
        'name' => 'required',
    ];

    public function author()
    {
        return $this->belongsTo('App\Author');
    }

    public function post()
    {
        return $this->belongsTo('App\Post');
    }
}

app/Http/Controllers/CommentController.php
<?php

namespace App\Http\Controllers;

use App\Comment;
use App\Post;
use App\Http\Requests\StoreComment;
use Illuminate\Http\Request;

class CommentController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth', ['except' => ['index', 'show']]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $comments = Comment::all();

        return view('comments.index', compact('comments'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create($post_id)
    {
        $author = auth()->user()->author;
        $post = Post::findOrFail($post_id);

        return view('comments.create', compact('author', 'post'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreComment $request)
    {
        $comment = Comment::create($request->validated());

        // TODO: fire an event, like https://laravel.com/docs/5.8/events#dispatching-events
        // event(new CommentStored($comment));
        return redirect()->route('posts.show', ['id' => $comment->post->id]);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Comment  $comment
     * @return \Illuminate\Http\Response
     */
    public function show(Comment $comment)
    {
        $comments = [$comment];

        return view('comments.index', compact('comments'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Comment  $comment
     * @return \Illuminate\Http\Response
     */
    public function edit(Comment $comment)
    {
        return view('comments.edit', compact('comment'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Comment  $comment
     * @return \Illuminate\Http\Response
     */
    public function update(StoreComment $request, Comment $comment)
    {
        $validated = $request->validated();

        $comment->title = $validated['title'];
        $comment->content = $validated['content'];
        $comment->save();

        // TODO: fire an event, like https://laravel.com/docs/5.8/events#dispatching-events
        // event(new CommentUpdated($comment));
        return redirect()->route('posts.show', ['id' => $comment->post->id]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Comment  $comment
     * @return \Illuminate\Http\Response
     */
    public function destroy(Comment $comment)
    {
        $return_id = $comment->post->id;
        $succeeded = $comment->delete();

        if ($succeeded) {
            $message = 'Comment is successfully deleted';
        } else {
            $message = 'Comment failed to be deleted';
        }

        // TODO: fire an event, like https://laravel.com/docs/5.8/events#dispatching-events
        // event(new CommentDestroyed($comment));
        return redirect()->route('posts.show', ['id' => $return_id])->with('status', $message);
    }
}

resources/views/comments/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card-body">
                @if (session('status'))
                    <div class="alert alert-success" role="alert">
                        {{  session('status') }}
                    </div>
                @endif

                <div class="card uper">
                    <div class="card-header">
                        Add Comment
                    </div>
                    <div class="card-body">
                        @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                <li>{{  $error }}</li>
                                @endforeach
                            </ul>
                        </div><br />
                        @endif
                        <form method="post" action="{{ route('comments.store') }}">

                            @csrf
                            <input type='hidden' name='author_id' value='{{ $author->id }}'>
                            <input type='hidden' name='post_id'   value='{{ $post->id }}'>

                            <div class="form-group">
                                <label for="name">Comment Title:</label>
                                <input type="text" class="form-control" name="title"/>
                            </div>
                            <div class="form-group">
                                <label for="content">Comment Content :</label>
                                <textarea class="form-control" name="content"></textarea>
                            </div>

                            <p class='small'>
                                author id:{{ $author->id }}
                                author name:{{ $author->name }}
                                author ip:{{ $author->ip }}
                            </p>

                            <button type="submit" class="btn btn-primary">Create Comment</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/comments/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card-body">
                @if (session('status'))
                    <div class="alert alert-success" role="alert">
                        {{ session('status') }}
                    </div>
                @endif

                <div class="card uper">
                    <div class="card-header">
                        Edit Comment
                    </div>
                    <div class="card-body">
                        @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div><br />
                        @endif
                        <form method="post" action="{{ route('comments.update', $comment->id) }}">

                            @csrf
                            @method('PATCH')
                            <input type='hidden' name='author_id' value='{{ $comment->author->id }}'>
                            <input type='hidden' name='post_id'   value='{{ $comment->post->id }}'>

                            <div class="form-group">
                                <label for="name">Comment Title:</label>
                                <input type="text" class="form-control" name="title" value="{{ $comment->title }}"/>
                            </div>
                            <div class="form-group">
                                <label for="content">Comment Content :</label>
                                <textarea class="form-control" name="content">{{ $comment->content }}</textarea>
                            </div>

                            <p class='small'>
                                author id:{{ $comment->author->id }}
                                author name:{{ $comment->author->name }}
                                author ip:{{ $comment->author->ip }}
                            </p>

                            <button type="submit" class="btn btn-primary">Update Comment</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/comments/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card-body">
                @if (session('status'))
                    <div class="alert alert-success" role="alert">
                        {{ session('status') }}
                    </div>
                @endif

                @foreach($comments as $comment)
                <div class="card uper">
                    <div class="card-header">
                        {{ $comment->title}}<br />
                        <p class='small'>
                        id::{{ $comment->id}}
                        created_at::{{ $comment->created_at   }}
                        updated_at::{{ $comment->updated_at   }}
                        author->id::{{ $comment->author->id   }}
                        author->name::{{ $comment->author->name }}
                        author->ip::{{ $comment->author->ip   }}
                        </p>
                    </div>
                    <div class="card-body">
                        {{ $comment->content }}<br/><br/>
                        <form action="{{ route('posts.show', ['id' => $comment->post->id]) }}" method="get">
                            @csrf
                            <button class="btn" type="submit">cancel</button>
                        </form>&nbsp;
                        <form action="{{ route('comments.edit', $comment->id) }}" method="get">
                            @csrf
                            <button class="btn btn-primary" type="submit">edit</button>
                        </form>&nbsp;
                        <form action="{{ route('comments.destroy', $comment->id) }}" method="post">
                            @csrf
                            @method('DELETE')
                            <button class="btn btn-danger" type="submit">delete</button>
                        </form>
                    </div>
                </div>
                @endforeach
            </div>
        </div>
    </div>
</div>

@endsection